# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/01_CodeLearning/01_FPGA_Verilog_Prj/02_LEDBlink_20240505/02_Project/LED_Blink/LED_Blink.srcs/sources_1/ip/CLK_PLL/CLK_PLL.xci
# IP: The module: 'CLK_PLL' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/01_CodeLearning/01_FPGA_Verilog_Prj/02_LEDBlink_20240505/02_Project/LED_Blink/LED_Blink.gen/sources_1/ip/CLK_PLL/CLK_PLL_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLK_PLL'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/01_CodeLearning/01_FPGA_Verilog_Prj/02_LEDBlink_20240505/02_Project/LED_Blink/LED_Blink.gen/sources_1/ip/CLK_PLL/CLK_PLL.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLK_PLL'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/01_CodeLearning/01_FPGA_Verilog_Prj/02_LEDBlink_20240505/02_Project/LED_Blink/LED_Blink.gen/sources_1/ip/CLK_PLL/CLK_PLL_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLK_PLL'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: e:/01_CodeLearning/01_FPGA_Verilog_Prj/02_LEDBlink_20240505/02_Project/LED_Blink/LED_Blink.srcs/sources_1/ip/CLK_PLL/CLK_PLL.xci
# IP: The module: 'CLK_PLL' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/01_CodeLearning/01_FPGA_Verilog_Prj/02_LEDBlink_20240505/02_Project/LED_Blink/LED_Blink.gen/sources_1/ip/CLK_PLL/CLK_PLL_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLK_PLL'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/01_CodeLearning/01_FPGA_Verilog_Prj/02_LEDBlink_20240505/02_Project/LED_Blink/LED_Blink.gen/sources_1/ip/CLK_PLL/CLK_PLL.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLK_PLL'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/01_CodeLearning/01_FPGA_Verilog_Prj/02_LEDBlink_20240505/02_Project/LED_Blink/LED_Blink.gen/sources_1/ip/CLK_PLL/CLK_PLL_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLK_PLL'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
